language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
    - "nightly"
install:
    - "pip install tox"
    - "pip install coveralls"
script: 
    - "tox -e py -e flake8"
matrix:
    allow_failures:
        - python: "3.2"
        - python: nightly
        - python: pypy
        - python: pypy3
after_success:
    coveralls
